name: Deploy Frontend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build Project
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
        env:
          PUBLIC_API_URL: https://api.iluminacion-hernandez.com

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist,package.json,pnpm-lock.yaml"
          target: "~/apps/frontend"

      - name: Restart App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/apps/frontend
            pnpm install --prod
            pm2 restart astro-front || PORT=4321 pm2 start dist/server/entry.mjs --name "astro-front"
            pm2 save